### PR TITLE
Css fetching

### PR DESCRIPTION
**Pull request by oluoluoxenfree**
## Steps to test/reproduce
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

## Show me
_Provide screenshots/animated gifs/videos if necessary._

# REMEMBER: Attach this PR to the Trello card

### CODE REVIEW

**Comment by oluoluoxenfree** [comment]
[fetchCSS() function](https://trello.com/c/PFPtLG1P/35-fetchcss-function)

**Review by jgerigmeyer — APPROVED** [review]
@oluoluoxenfree This looks good to merge as far as I'm concerned -- please review the dev-tooling changes and let me know if you have any suggestions or questions!

**Comment by oluoluoxenfree** [comment]
@jgerigmeyer i might have missed it, but what transforms the typescript?

**Comment by jgerigmeyer** [comment]
> @jgerigmeyer i might have missed it, but what transforms the typescript?

@oluoluoxenfree Right now [Vite](https://vitejs.dev/) is handling the transforms, as defined in [vite.config.ts](https://github.com/oddbird/css-anchor-positioning/blob/50dadc19caaadd95c39f50d245b9d329abd0201d/vite.config.ts). I think it should be able to handle what we need -- it uses esbuild in dev and Rollup in production.

**Pull request merged**
