### PR TITLE
Fix edge cases with CSS custom properties.

### PR DESCRIPTION
**Pull request by jgerigmeyer**

### CODE REVIEW

**Comment by jgerigmeyer** [comment]
[Handle cases where there are multiple CSS custom properties with the same name.](https://trello.com/c/UGEMTfVc/66-handle-cases-where-there-are-multiple-css-custom-properties-with-the-same-name)

**Comment by jgerigmeyer** [comment]
[When an anchor fn is applied to a custom property, trace usage even if that prop is then applied to another custom property.](https://trello.com/c/yOP9vqxZ/65-when-an-anchor-fn-is-applied-to-a-custom-property-trace-usage-even-if-that-prop-is-then-applied-to-another-custom-property)

**Comment by jgerigmeyer** [comment]
[transformCSS() - anchor() function in math functions](https://trello.com/c/YAl95oDi/26-transformcss-anchor-function-in-math-functions)

**Comment by jgerigmeyer** [comment]
@mirisuzanne I think I got it to work for an arbitrary number of custom property re-assignments/pass-throughs! I still need to update some tests, but take a look at the new demos and see what you think. 🙏

**Comment by mirisuzanne** [comment]
@jgerigmeyer impressive! Looks good to me.

**Review by mirisuzanne — APPROVED** [review]

**Comment by jgerigmeyer** [comment]
@sanajaved7 There's a lot here, and I'm sure this could be cleaner. I'd appreciate your review, and it might be most efficient to walk through the changes together?

**Comment by sanajaved7** [comment]
@jgerigmeyer still catching up so it would definitely help to review together!

**Comment by jgerigmeyer** [comment]
> @jgerigmeyer still catching up so it would definitely help to review together!

@sanajaved7 Makes sense -- propose a time on the calendar?

**Review by sanajaved7 — APPROVED** [review]
Thanks for tackling this! This looks good to me and I feel good about the follow-up plan to separate out the custom property parsing logic to share with other polyfills 🎉

**Comment by sanajaved7** [comment]
Test comment ?

**Pull request merged**
